### ISSUE TITLE
update readme file

### ISSUE THREAD

**Issue by bharat-kadchha** [bharat-kadchha/practicals#11]
check out the below link  
https://github.com/bharat-kadchha/Core-And-Advance-Java-Practicals/tree/master/spring-framework

please modified the **main title of Readme** as per the **directory structure**

**Comment by iprinceroyy** [comment]
can you assign it to me?

**Comment by bharat-kadchha** [comment]
Hey brother, I appreciate you interest in open source and also for
hactoberfest 2021.

Let's contribute in eachother repos.you create one issue for me and I will
assign my issue to you.
By this we both will get 1 PR.

Thank you for reaching out to me.
