### ISSUE TITLE
Update the Readme file

### ISSUE THREAD

**Issue by bharat-kadchha** [bharat-kadchha/practicals#12]
check out the below link: 
https://github.com/bharat-kadchha/Core-And-Advance-Java-Practicals/tree/master/advance-java

please read the readme file carefully and did changes in the line of the **java-mail-API** sub-topic.

**Comment by irffanasiff** [comment]
Can i work on this issue

**Comment by yogesh5259** [comment]
I am ready to work on this issue.

**Comment by bharat-kadchha** [comment]
this issue solves by the @yogesh5259 .
